### ISSUE TITLE
Replace zimwriterfs with node-zimlib

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#10]
Should allow to be faster and easier to install
https://github.com/cscott/node-libzim

**Comment by kelson42** [comment]
@midik Link is wrong, this is the module https://www.npmjs.com/package/@openzim/libzim

**Comment by midik** [comment]
struggling with this currently
![image](https://user-images.githubusercontent.com/6795530/76760262-60845380-679e-11ea-9642-9dd13cd96b08.png)

**Comment by kelson42** [comment]
@you have to specify the main page. This is a metadata. See how this is done in MWoffliner. Here is the list of all possible Metadata in a ZIM, https://wiki.openzim.org/wiki/Metadata

**Comment by kelson42** [comment]
In fact this is in the header, so this is not exactly a metdata, see https://wiki.openzim.org/wiki/ZIM_file_format#Header

**Comment by kelson42** [comment]
@midik See https://github.com/openzim/mwoffliner/blob/master/src/mwoffliner.lib.ts#L371

**Comment by midik** [comment]
thank you for suggestions... actually, I already saw those above. Probably I just missed something, there's no magic, so I'm debugging :)
