### ISSUE TITLE
PhET ZIM files contain incorrect date

### ISSUE THREAD

**Issue by holta** [openzim/phet#116]
Example 1:

[phet_en_2021-01.zim](http://download.kiwix.org/zim/phet/phet_en_2021-01.zim)
[phet_es_2021-01.zim](http://download.kiwix.org/zim/phet/phet_es_2021-01.zim)
[phet_fr_2021-01.zim](http://download.kiwix.org/zim/phet/phet_fr_2021-01.zim)

...contain the date 2021-**_00-00_** when they should contain the date 2021-**_01-03_** &mdash; MM and DD are **both** off in January.
<br>
Example 2:

[phet_en_2021-02.zim](http://download.kiwix.org/zim/phet/phet_en_2021-02.zim)
[phet_es_2021-02.zim](http://download.kiwix.org/zim/phet/phet_es_2021-02.zim)
[phet_fr_2021-02.zim](http://download.kiwix.org/zim/phet/phet_fr_2021-02.zim)

...contain the date 2021-**_01_**-03 when they should contain the date 2021-**_02_**-03 &mdash; only MM is off for all other months?
<br>
Similarly http://download.kiwix.org/library/library_zim.xml contained incorrect dates as above.

Apologies if this issue should be reported to another repo?

**Comment by kelson42** [comment]
Similar to #106.... a bit surprised it is still buggy.
