### ISSUE TITLE
PhET experiments load Google Analytics script and other online content

### ISSUE THREAD

**Issue by Jaifroid** [openzim/phet#127]
I was surprised to find my ad-blocker had blocked elements from a PhET experiment running in an offline ZIM (`phet_en_2021-06.zim`. On investigation it turns out that all experiments load a live Google Analytics script. See code snapshot below. Can this be removed at source? I think most users of offline ZIMs are pretty privacy conscious and not all Kiwix clients can automatically block external content from loading.

![image](https://user-images.githubusercontent.com/4304337/122001148-c8fa2000-cda7-11eb-8be1-d107bf508836.png)

**Comment by kelson42** [comment]
wow, good catch, yes it has to be removed

**Comment by Jaifroid** [comment]
OK. JFYI, the "other online content" referred to in the title of this issue are a couple of links back to phet.colorado.edu:

![image](https://user-images.githubusercontent.com/4304337/122003476-11670d00-cdab-11eb-9c86-e8db5f653c1e.png)

**Comment by kelson42** [comment]
Both of these entries should simply be removed IMO. None of them make sense in an offline context.
