### ISSUE TITLE
Use ESLint instead of TSLint

### ISSUE THREAD

**Issue by pavel-karatsiuba** [openzim/phet#184]
TSLint has been deprecated as of 2019.
Use ESLint with modern rules.

**Comment by kelson42** [comment]
Seems indeed necessary.

**Comment by kelson42** [comment]
@pavel-karatsiuba Two questions:
* when the linter is run? It’s run a compilation time? At test time? Need a special command?
* Is this run by the CI automatically? Does the CI fails if linter reports an error?

**Comment by pavel-karatsiuba** [comment]
> @pavel-karatsiuba Two questions:
> 
> * when the linter is run? It’s run a compilation time? At test time? Need a special command?
> * Is this run by the CI automatically? Does the CI fails if linter reports an error?

Linter is an additional script and the developer should run linter before push commits.
CI runs the linter and CI fails if the linter return error.

**Comment by kelson42** [comment]
@pavel-karatsiuba Could you please do that one, we need anyway to deprecate tslint.
