### ISSUE TITLE
Tuning up building process

### ISSUE THREAD

**Issue by pavel-karatsiuba** [openzim/phet#187]
Change the building process to separate compiled js files from other code. They should be in a separate folder.
Also do not build js files that are not used.

**Comment by kelson42** [comment]
Not super convinced by the added value of such an effort.

**Comment by pavel-karatsiuba** [comment]
@kelson42 
This project is written using Typescript. To execute Typescript from the command line we don't need to build js files from ts files.
We need to build only one js file and copy it into zim file. But we are building them all on the `export` step.

So make sense to change the configuration and not build all *.ts files. Because this process takes some time.
This is a 1-hour task.

**Comment by kelson42** [comment]
Ok, please fix
