### ISSUE TITLE
Language selector missing languages

### ISSUE THREAD

**Issue by Popolechien** [openzim/phet#192]
![phet](https://user-images.githubusercontent.com/21675885/214255425-aadb8287-0f4d-4f2f-85b8-4918ef402d16.png)
Looks like hebrew, indonesian, and at least two more are not listed (clicking on them does change the language settings for the content though

Tested on Android App 2020-04 Build:6200950

**Comment by Popolechien** [comment]
Tested again with latest zim (2023-01-01) and language defaults to device's default, so not sure the issue is entirely valid (except that the app should be updated, of course).

**Comment by kelson42** [comment]
@Popolechien works for me, please forve refresh browser and put screenshot with url of library.kiwix.org.

**Comment by Popolechien** [comment]
@kelson42 As indicated looks like the issue is on the Android app - so either with Android itself or the old zim. I'll close.
