### ISSUE TITLE
Duplicate phet ZIM files

### ISSUE THREAD

**Issue by MohitMaliFtechiz** [openzim/phet#204]
These two phet ZIM files are same size , same content and ISO code which is return by zim file ```eng```. 
https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-ca_2023-01.zim
https://mirrors.dotsrc.org/kiwix/zim/phet/phet_en-gb_2023-01.zim

Only difference is the file name in my opinion we should not rely on file name rather than metadata and seems like both file are returning same metadata.

**Comment by kelson42** [comment]
@pavel-karatsiuba To me it sounds logic that they are really similar, because they use almost the same language. But we have something fishy around the `Language` metadata.

**Comment by pavel-karatsiuba** [comment]
I have made PR with changes. But I think we need to make it in a different way.
This is my proposition: #207
