### ISSUE TITLE
Incorrect Name metadata

### ISSUE THREAD

**Issue by rgaudin** [openzim/phet#205]
According to the https://github.com/openzim/overview/wiki/Naming-Convention, the `Name` metadata is incorrect in phet created ZIM files.

It is currently: `phets_afr` while it should be `phets_af_all` for instance: ISO-639-1 language code and selection/all specifier.

This is based on 2023-03-01 run

**Comment by kelson42** [comment]
@pavel-karatsiuba please update. This is indeed a convention we have that we don't respect. Shoukd be straight.

**Comment by pavel-karatsiuba** [comment]
@kelson42 
phet zim can be multilingual so the metadata Name will be equal to `phets_mul`. Which language do I need to set in this case?

**Comment by kelson42** [comment]
Yes, "phet_mul_all"

**Comment by rgaudin** [comment]
Given you've agreed to use the `_all` *selection specifier* in the `Name`, is there a reason not to use it in the filename?

The convention suggests using the same because it avoids confusion ans most likely simplifies maintenance.

```
phet_mul_2023-03.zim
- Language: afr,sqi,amh,ara,hye,aym,aze,bak,eus,bel,ben,bis,bos,bul,mya,cat,nya,zho,zho,zho,hrv,ces,dan,nld,eng,est,fao,fin,fra,fur,glg,lug,kat,deu,ell,guj,hat,hau,heb,hin,hun,isl,ibo,ind,gle,ita,jpn,kan,kaz,khm,kik,kin,kor,kur,lao,lav,lit,mkd,msa,mal,mlt,mri,mar,ron,mon,nep,nob,nno,ori,orm,pus,fas,pol,por,ron,rus,srp,hbs,snd,sin,slk,slv,sot,spa,swa,swe,tgl,tgk,tam,tel,tha,bod,tir,tsn,tur,tuk,twi,ukr,urd,uzb,vie,cym,wol,xho,yor
- Name: phets_mul_all
```

```
phet_af_2023-03.zim
- Language: afr
- Name: phets_af_all
```

Let me know if you decide to change the name so I'll cleanup the folder.
