### ISSUE TITLE
Replace current logo

### ISSUE THREAD

**Issue by Popolechien** [openzim/phet#21]
We currently talking with PhET who would like to keep their current logo for University of Colorado material (they have their own app on iOS). They kindly offered that we used the attached as a replacement - for the Android and zim (well, pretty much everywhere the old logo was).

![phet](https://cloud.githubusercontent.com/assets/21675885/22298823/31208e14-e322-11e6-87ef-381c7c4a2258.png)

**Comment by kelson42** [comment]
done

**Comment by kelson42** [comment]
We should also replace the logo in the banner in the zim

**Comment by kelson42** [comment]
This has been done with the new welcome page.
