### ISSUE TITLE
Exercises without names

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#31]
Content labels: there are a couple of exercises seemingly without names. They happen to be duplicates.
Reported by @julianharty

**Comment by kelson42** [comment]
@julianharty Can not reproduce that problem. It probably has been fixed by @ISNIT0 in April. Please reopen the ticket with a concrete screenshot/example if you still can reproduce the problem.

**Comment by julianharty** [comment]
Will do, I had screenshots at the time, however I agree it's probably better to retest.
