### ISSUE TITLE
Compiling zim files uses a lot of processing power

### ISSUE THREAD

**Issue by hayleynewton** [openzim/phet#33]
Command used - "npm run export"

This process seems to be using a lot of the CPU, see image below.
Macbook is running physically hot when compiling the zim file.

<img width="492" alt="screen shot 2017-04-06 at 20 27 22" src="https://cloud.githubusercontent.com/assets/17700924/24772138/12e118b0-1b08-11e7-84b5-ecda288755ee.png">

**Comment by kelson42** [comment]
@hayleynewton This looks pretty normal to me as the process is CPU/IO intensive. This tasks are necessary. I do not really understand what is wrong with getting a hot computer?

**Comment by kelson42** [comment]
@hayleynewton I don't think we can do much against this.
