### ISSUE TITLE
ELIFECYCLE error. TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by nobicycle** [openzim/phet#35]
$ npm -v
5.3.0

$ npm run transform

> phetscraper@1.0.0 transform /home/archives/Education/Phet/phet/phet-master
> node steps/transform.js

Compressing images, this will take a while
/home/archives/Education/Phet/phet/phet-master/steps/transform.js:92
    html = htmlSplit[0] + htmlSplit[1].split('// ### END THIRD PARTY LICENSE ENTRIES ###')[1];
                                      ^

TypeError: Cannot read property 'split' of undefined
    at removeStrings (/home/archives/Education/Phet/phet/phet-master/steps/transform.js:92:39)
    at /home/archives/Education/Phet/phet/phet-master/steps/transform.js:157:16
    at Array.forEach (native)
    at Object.<anonymous> (/home/archives/Education/Phet/phet/phet-master/steps/transform.js:152:6)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Function.Module.runMain (module.js:605:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1

[2017-08-13T18_50_10_567Z-debug.log.txt](https://github.com/openzim/phet/files/1220679/2017-08-13T18_50_10_567Z-debug.log.txt)

npm ERR! phetscraper@1.0.0 transform: `node steps/transform.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the phetscraper@1.0.0 transform script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2017-08-13T18_50_10_567Z-debug.log

npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/adrian/.npm/_logs/2017-08-13T18_50_10_567Z-debug.log

**Comment by kelson42** [comment]
Thx for the report, will try to reproduce the bug.

**Comment by kelson42** [comment]
@nobicycle I can not reproduce the problem. What is your version of nodejs?
@ISNIT0 any idea?

**Comment by nobicycle** [comment]
$ node -v
v8.2.1

I don't know whether the command sequence and aborts have anything to do with it.
First used 'npm run setup' and ran out of internet quota.
Next I ran 'npm run get' but noticed with all languages being pulled I would also run out of internet quota, so I aborted.
I edited the json file to limit the build to english and re-ran  'npm run get', which succeeded.
Then I ran ' npm run transform' and got the error.

**Comment by kelson42** [comment]
@nobicycle Could you please clean everything, rerun things cleanly from the beginning and, if you still have an issue, publish here the whole set of command you run?

**Comment by kelson42** [comment]
@nobicycle BTW, what do you try to do? We publish already ZIM files in all languages you know? http://download.kiwix.org/zim/phet/

**Comment by nobicycle** [comment]
Hi kelson42
Exactly! :-) 
I already have phet_en.zim, downloaded from Kiwix but the file never opened properly, in more than one client. Here for example the Kizix client:

> Unable to load '/media/esata/MEDIA/System/Kiwix/data/content/phet_en.zim'. Are you sure this is a ZIM file?

However, I just downloaded phet_en_2017-08.zim from the link you gave and it worked!!!

Thanks very much.

**Comment by nobicycle** [comment]
I spoke prematurely.
The file opens but the opening screen presents no content index.
(Kiwix client)
![phet-opening-screen](https://user-images.githubusercontent.com/1372447/29301759-10124518-81b1-11e7-8255-ca5a89073ea6.png)

One has to use Search or Random to have a simulation running.

When I run Kiwix server and open Phet in a browser I get the following in the console:
![phet-console](https://user-images.githubusercontent.com/1372447/29301790-45cc10c6-81b1-11e7-9842-1e69352295c0.png)

**Comment by nobicycle** [comment]
The console log
[phet-127.0.0.1-1502769840895.log.txt](https://github.com/openzim/phet/files/1224110/phet-127.0.0.1-1502769840895.log.txt)

**Comment by kelson42** [comment]
@nobicycle Yes, the desktop version of Kiwix is a mess on that file. This is a known issue. Have you tried to enjoy it through the server (menu tools > server) ? Maybe it work better?

**Comment by nobicycle** [comment]
Yes kelson42, the above screenshot is the Kiwix server and Opera browser. Also the same result with the python Zimply client.
Anyhow, thanks for the help. I am happy  PHET can be used via search in the Kiwix client, provided one knows the names of course (attached)
[phet-list.txt](https://github.com/openzim/phet/files/1224870/phet-list.txt)

**Comment by kelson42** [comment]
I have published new ZIM files and It works perfectly with kiwix-serve nightly version: http://download.kiwix.org/nightly/2017-09-13/
