### ISSUE TITLE
Welcome page should be improved

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#37]
The welcome page works well but:
* It should be more fancy from the colors
* A few details should be improved on the design to make it more appealing.

**Comment by kelson42** [comment]
@midik Few remarks on this. For the moment I would:
* Remove the color filter on thumbnails
* make a pointer cursor over the thumbnails.

Do you have maybe proposals on your side to make this home page less buggy/more appealing?

**Comment by midik** [comment]
I made that above, plus:
- made language and category selectors more clean;
- changed overlay's color to fit the common color style;
- made overlay's multi-line text carries to the next line better;
- slightly reduced overlay height;

**Comment by kelson42** [comment]
@midik Thank you. I re-open that one because I want:
* pointer to be a "hand" (clickable) hover the sim thumnails
* I want to remove the blue color filter (at least if the mouse is "hover). Maybe you have a preference here.

**Comment by midik** [comment]
I made these two thing already...

**Comment by kelson42** [comment]
@midik I don't see it neither with Firefox nor with Chromium (using kiwix-serve). See screenshot (the mouse was over second simulation thumbnail):
![image](https://user-images.githubusercontent.com/1029718/77846838-2a40ce00-71b9-11ea-9872-f7a22cf90d65.png)

**Comment by midik** [comment]
@kelson42 could some kind of caching causes that on your side?

(gif 7Mb)
![1](https://user-images.githubusercontent.com/6795530/78266427-715af600-750e-11ea-8d46-3a88bc67fc95.gif)

**Comment by kelson42** [comment]
@midik Really strange, it works here http://library.kiwix.org/phet_fr_2020-03/A/index.html but was definitly not working on my computer (even after purging cache). I'll close the ticket as something seems really wrong locally. Sorry for the burden.
