### ISSUE TITLE
Missing favicon in /-/favicon

### ISSUE THREAD

**Issue by rgaudin** [openzim/phet#54]
Although ZIM file contains a favicon, it's not available through the `/-/favicon` URI.

* [`/phet_en_2019-06/-/favicon`](http://library.kiwix.org/phet_en_2019-06/-/favicon) **does not exists**
* [`/meta?content=phet_en_2019-06&name=favicon`](http://library.kiwix.org/meta?content=phet_en_2019-06&name=favicon) **exists** 

@kelson42 shouldn't the zim tool used by this scrapper take care of this? Otherwise it's hardly reliable.

**Comment by kelson42** [comment]
Strongly suspect this is because https://github.com/openzim/zimwriterfs/issues/119. We should wait and see if fix that bug also fix this one.

**Comment by kelson42** [comment]
@midik This is bug is still there. Favicon is not at the right place like specified in [the spec](https://wiki.openzim.org/wiki/Metadata#Favicon). I assume this would be easy to fix.

**Comment by midik** [comment]
not sure that bug is still here:
![image](https://user-images.githubusercontent.com/6795530/77104768-97bc6400-6a2d-11ea-8f89-0b1ab049d64b.png)
if so, could you please suggest how I can reproduce it?

**Comment by kelson42** [comment]
I will check again then...

**Comment by kelson42** [comment]
@midik The `favicon.ico` is I guess the HTML page favicon, here we are talking about the ZIM `favicon.png` (see spec).

If I make `zimdup -l -i` I get the full log and you can see that the `favicon.png` is in the `I`  namespace:
```
url: favicon.png
»       title:           favicon.png
»       idx:             141
»       namespace:       I
»       type:            article
»       mime-type:       image/png
»       article size:    2941
```

You can as well see that by testing the file with `kiwix-serve`.

**Comment by kelson42** [comment]
@midik Looks good now indeed.
