### ISSUE TITLE
Introduce localization of the scraper

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#85]
If many translations come from the Phets web site, a few things are hardcoded in the app. We should have proper string files and then sync with Translatewiki.

**Comment by kelson42** [comment]
@translatewiki @nikerabbit @Abijeet What would be the best format here to use? Kiwix/openZIM has so far never used Translatewiki for a Node.js project!

**Comment by Abijeet** [comment]
Hi @kelson42 

This library can be used to handle i18n - https://github.com/wikimedia/banana-i18n. It uses simple JSON files.

**Comment by kelson42** [comment]
Don’t forget to read #162 too
