### ISSUE TITLE
Visual improvments around select boxes

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#88]
I want to have the following:
* "category" box always under "language" box (not beside like today)
* Both boxes centered, but select boxes should be perfectly aligned vertically
* Label should be "Language" instead of "Selected language:"
* Label should be "Category" instead of "Categories"
* "All" in categories select box should be labeled with "" (empty string), like that this is perfectly translated ;)

**Comment by midik** [comment]
is this still actual after closing #37 ?
![image](https://user-images.githubusercontent.com/6795530/78269097-ca785900-7511-11ea-8215-d4e0b6d899a4.png)

**Comment by kelson42** [comment]
@midik I mostly want to secure that is display like this in responsive mode / small screens. Could you secure that. For broader screen, it would be indeed better, just side by side (in particular now that you have removed the labels).

**Comment by midik** [comment]
I took this into account with those changes so it looks descent down to 300px width ;)
![2](https://user-images.githubusercontent.com/6795530/78271026-50959f00-7514-11ea-98cf-c046129818ec.gif)

**Comment by kelson42** [comment]
Good, if you can just add a bit of margin left and right, so the select boxes never touch the borders like they do currently.

**Comment by midik** [comment]
done - in master
