### ISSUE TITLE
A few languages are not translated properly in the language list

### ISSUE THREAD

**Issue by kelson42** [openzim/phet#90]
In think about "fu" and "sh". Why? Can we do something about it?

**Comment by midik** [comment]
@kelson42 there's no category index page like `https://phet.colorado.edu/fr/simulations/category/physics` for these languages. So, `get` logic falls back to english with message:
```
2020-03-30 18:38:22 [warn]:     The following (2) language(s) will use english metadata: fu, sh
```
I guess we can follow some other way (like #85) but I'm not sure this would be a priority at the moment. However, you're a captain ;)

**Comment by kelson42** [comment]
Transforming the language ISO code to the language name in the language should IMO be done via a npm package.

**Comment by midik** [comment]
Ah, yes. I just misunderstood so I was talking about the ways to get the categories tree for the languages which haven't translated originally.
Regarding of this task, sure, that's doable.

**Comment by kelson42** [comment]
To me not fixed in https://download.kiwix.org/zim/phet/phet_mul_2020-04.zim
